name: Roxxlen APK Uret
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Al
        uses: actions/checkout@v4
      
      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Mobil Altyapıyı (Flutter) Hazırla
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          - name: Flet'i Yükle
        run: pip install flet==0.28.3
          
      - name: APK Derleme İşlemini Başlat
        run: flet build apk
        
      - name: Hazır APK Dosyasını Sun
        uses: actions/upload-artifact@v4
        with:
          name: Roxxlen-Depo-APK
          path: build/apk/**/*.apk
